#------------------------
# github actions basic
# Anthony Bassplayer
#------------------------
# This is a basic workflow to help you get started with Actions

name: my_git_action1
env:
  APPLICATION_NAME: "My Py"
  DEPLOY_PACKAGE_NAME: "py_deploy_ver-${{ github.sha }}"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in my-test
        run : echo "Hello World!"
        
      - name: Execute few commands 
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: ls -la
        
        #check всего репозитория и склонировать
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder
        run: ls -la

  my-deploy:
    needs: [my-test]
    runs-on: ubuntu-latest
    env:
      VAR1: "This is job lvl VAR1"
      VAR2: "This is job lvl VAR2"

    steps: 
      - name: Print Hello Message in my-deploy
        run : echo "Hello World!"
        
      - name: Print env vars
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is super local evrmnt var!"
        
      - name: Printing Deployment package
        run: echo "Deploy Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
      - name: let's test some packages if they are here 1
        run: aws --version
     
      - name: let's test some packages if they are here 2
        run: zip
