#------------------------
# github actions basic
# Anthony Bassplayer
#------------------------
# This is a basic workflow to help you get started with Actions

name: my_git_action1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in my-test
        run : echo "Hello World!"

  my-deploy:
    needs: [my-test]
    runs-on: ubuntu-latest 
    steps: 
      - name: Print Hello Message in my-deploy
        run : echo "Hello World!"    
